### ISSUE TITLE
My post, oh, my post

### ISSUE THREAD

**Issue by lucasconstantino** [mstn/apollo-local-network-interface#2]
You basically deprecated most of this [post of mine on medium](https://medium.com/taller-team/graphql-today-using-apollo-for-applications-that-still-depend-on-rest-apis-839895ce20d0) with this package.  At least I do explain to people how to build it your own, and my focus was much on beginners, so that "GraphQL server on the browser? Huh" feeling is mostly covered there haha.

Anyway, just passing to say thanks for this project and I've added recommendations for it on that post ;)

**Comment by mstn** [comment]
Hi @lucasconstantino sorry for the late reply and thanks for citation! I read your post. Very nicely written.

**Comment by mstn** [comment]
I added your post to the references. I am sure it could be useful to understand what the package does.
