### ISSUE TITLE
Doesn't seem to work with Apollo 2.0

### ISSUE THREAD

**Issue by mlabrum** [mstn/apollo-local-network-interface#4]
Hey,

Just tried this with Apollo 2.0 and it seems they removed the `networkInterface` and now have `link`

Cheers,

**Comment by mlabrum** [comment]
I've setup a v2 version here https://github.com/mlabrum/apollo-link-local-schema

**Comment by mstn** [comment]
Hi @mlabrum thanks for testing it with Apollo 2.0 and for your work. I will have a look at Apollo 2, too.

**Comment by mstn** [comment]
@mlabrum I close this issue with Apollo 2 [apollo-link-schema](https://www.npmjs.com/package/apollo-link-schema) does what you need.
